export const ASSISTANT_LOG_LIST_REQUEST = 'ASSISTANT_LOG_LIST_REQUEST'
export const ASSISTANT_LOG_LIST_SUCCESS = 'ASSISTANT_LOG_LIST_SUCCESS'
export const ASSISTANT_LOG_LIST_FAIL = 'ASSISTANT_LOG_LIST_FAIL'
